### ISSUE TITLE
Attributeerror: 'torch.device' object has no attribute 'device'

### ISSUE THREAD

**Issue by YuxuanWen-Code** [ChenhongyiYang/QueryDet-PyTorch#37]
Hi, I was running the code but this problem occurs, here is the complete error message:
Traceback (most recent call last):
  File "/media/SSD/user1/QueryDet-PyTorch-main/train_coco.py", line 15, in <module>
    launch(
  File "/media/SSD/user1/QueryDet-PyTorch-main/detectron2/engine/launch.py", line 82, in launch
    main_func(*args)
  File "/media/SSD/user1/QueryDet-PyTorch-main/train_tools/coco_train.py", line 158, in start_train
    return trainer.train()
  File "/media/SSD/user1/QueryDet-PyTorch-main/apex_tools/apex_trainer.py", line 227, in train
    self.run_step()
  File "/media/SSD/user1/QueryDet-PyTorch-main/apex_tools/apex_trainer.py", line 249, in run_step
    loss_dict = self.model(data)
  File "/home/user1/.conda/envs/sr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/SSD/user1/QueryDet-PyTorch-main/models/querydet/detector.py", line 165, in forward
    return self.train_forward(batched_inputs, just_forward)
  File "/media/SSD/user1/QueryDet-PyTorch-main/models/querydet/detector.py", line 187, in train_forward
    all_anchors, all_centers = self.anchor_generator(all_features)
  File "/home/user1/.conda/envs/sr/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/SSD/user1/QueryDet-PyTorch-main/utils/anchor_gen.py", line 30, in forward
    anchors_over_all_feature_maps, centers_over_all_feature_maps = self._grid_anchors(grid_sizes)
  File "/media/SSD/user1/QueryDet-PyTorch-main/utils/anchor_gen.py", line 20, in _grid_anchors
    shift_x, shift_y = _create_grid_offsets(size, stride, self.offset, base_anchors.device)
  File "/media/SSD/user1/QueryDet-PyTorch-main/detectron2/modeling/anchor_generator.py", line 43, in _create_grid_offsets
    shifts_x = move_device_like(
  File "/home/user1/.conda/envs/sr/lib/python3.9/site-packages/torch/jit/_trace.py", line 1118, in wrapper
    return fn(*args, **kwargs)
  File "/media/SSD/user1/QueryDet-PyTorch-main/detectron2/layers/wrappers.py", line 146, in move_device_like
    return src.to(dst.device)
AttributeError: 'torch.device' object has no attribute 'device'

How can I resolve this? Many thanks

**Comment by itsrealkk** [comment]
It seems that you need to use detectron2 v0.2.1

**Comment by YuxuanWen-Code** [comment]
> It seems that you need to use detectron2 v0.2.1

Thank you very much! The program can run properly now.

Turns out I need detectron2 v0.2.1 +  fvcore 0.1.1
pip install fvcore==0.1.1.dev200512
