### ISSUE TITLE
Run the training code problem

### ISSUE THREAD

**Issue by koufeichou** [ChenhongyiYang/QueryDet-PyTorch#5]
Traceback (most recent call last):
  File "train_coco.py", line 6, in <module>
    from train_tools.coco_train import default_argument_parser, start_train
  File "/content/drive/My Drive/QueryDet-PyTorch-main/train_tools/coco_train.py", line 53, in <module>
    from models.backbone import build
ModuleNotFoundError: No module named 'models.backbone'

**Comment by ChenhongyiYang** [comment]
I have fixed the bug. Please try again :-)

**Comment by ailabnjtech** [comment]
thankyou
