### ISSUE TITLE
When I try to train the model,an AssertionError occurs.What should I do to train this model successfully?

### ISSUE THREAD

**Issue by GolvenDong** [ChenhongyiYang/QueryDet-PyTorch#52]
Traceback (most recent call last):
  File "train_visdrone.py", line 19, in <module>
    args=(args,),
  File "/home/golven/code/detectron2/detectron2/engine/launch.py", line 62, in launch
    main_func(*args)
  File "/home/golven/code/QueryDet-PyTorch/train_tools/visdrone_train.py", line 179, in start_train
    return trainer.train()
  File "/home/golven/code/QueryDet-PyTorch/apex_tools/apex_trainer.py", line 227, in train
    self.run_step()
  File "/home/golven/code/QueryDet-PyTorch/apex_tools/apex_trainer.py", line 249, in run_step
    loss_dict = self.model(data)
  File "/home/golven/.conda/envs/query-det/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/golven/code/QueryDet-PyTorch/models/retinanet/retinanet.py", line 197, in forward
    losses = self.det_loss(gt_classes, gt_deltas, box_cls, box_delta, self.focal_loss_alpha, self.focal_loss_gamma, self.cls_weights, self.reg_weights)
  File "/home/golven/code/QueryDet-PyTorch/models/retinanet/retinanet.py", line 278, in det_loss
    assert len(cls_weights) == len(pred_logits)
AssertionError

**Comment by Hiyuur** [comment]
> Traceback (most recent call last): File "train_visdrone.py", line 19, in args=(args,), File "/home/golven/code/detectron2/detectron2/engine/launch.py", line 62, in launch main_func(*args) File "/home/golven/code/QueryDet-PyTorch/train_tools/visdrone_train.py", line 179, in start_train return trainer.train() File "/home/golven/code/QueryDet-PyTorch/apex_tools/apex_trainer.py", line 227, in train self.run_step() File "/home/golven/code/QueryDet-PyTorch/apex_tools/apex_trainer.py", line 249, in run_step loss_dict = self.model(data) File "/home/golven/.conda/envs/query-det/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl result = self.forward(*input, **kwargs) File "/home/golven/code/QueryDet-PyTorch/models/retinanet/retinanet.py", line 197, in forward losses = self.det_loss(gt_classes, gt_deltas, box_cls, box_delta, self.focal_loss_alpha, self.focal_loss_gamma, self.cls_weights, self.reg_weights) File "/home/golven/code/QueryDet-PyTorch/models/retinanet/retinanet.py", line 278, in det_loss assert len(cls_weights) == len(pred_logits) AssertionError

Hello, I also have the same problem. How did you solve it?
