### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by syddpy666** [ChenhongyiYang/QueryDet-PyTorch#59]
Traceback (most recent call last):
  File "train_visdrone.py", line 15, in <module>
    launch(
  File "c:\users\lsy\desktop\querydet-pytorch-main\detectron2-windows\detectron2\engine\launch.py", line 82, in launch
    main_func(*args)
  File "C:\Users\lsy\Desktop\QueryDet-PyTorch-main\train_tools\visdrone_train.py", line 179, in start_train
    return trainer.train()
  File "C:\Users\lsy\Desktop\QueryDet-PyTorch-main\apex_tools\apex_trainer.py", line 234, in train
    self.run_step()
  File "C:\Users\lsy\Desktop\QueryDet-PyTorch-main\apex_tools\apex_trainer.py", line 256, in run_step
    loss_dict = self.model(data)
  File "D:\Anaconda\envs\QueryDet\lib\site-packages\torch\nn\modules\module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\lsy\Desktop\QueryDet-PyTorch-main\models\retinanet\retinanet.py", line 197, in forward
    losses = self.det_loss(gt_classes, gt_deltas, box_cls, box_delta, self.focal_loss_alpha, self.focal_loss_gamma, self.cls_weights, self.reg_weights)
  File "C:\Users\lsy\Desktop\QueryDet-PyTorch-main\models\retinanet\retinanet.py", line 278, in det_loss
    assert len(cls_weights) == len(pred_logits)
 

hello，how to solve this problem？

**Comment by ChenhongyiYang** [comment]
Hi, it's a bug, and we have fixed it right now.
